### PR TITLE
Adding sampledata plugin for JED

### PR DESCRIPTION
**Pull request by Hackwar**
What the title says. The plugin already works, ~~however the SQL needs some more fine tuning. I will do that in an additional PR. Also the translation files still need to be done...~~ All done.

### CODE REVIEW

**Comment by Hackwar** [comment]
The optimized SQL resulted in the queries running several times faster, so this should hopefully help others to setup their systems.

**Comment by mfleeson** [comment]
Would it be a good idea to put
SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;
Around the sql.

**Comment by Hackwar** [comment]
There are no foreign keys in the current SQL. While we should maybe introduce that at some point, it isn't necessary right now.

**Comment by mfleeson** [comment]
Oh that's right. There was in JED3 and it made it a nightmare so left them out whilst I was prototyping.

**Pull request merged**
